blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/gofred-io/gofred-cli/discussions
    about: Please ask and answer questions here.
  - name: Documentation
    url: https://github.com/gofred-io/gofred-cli#readme
    about: Check the documentation for common questions and usage examples.
